version: '3.9'
x-mariadb-envvars:
  MYSQL_ROOT_PASSWORD: '${VIPGO_MYSQL_ROOT_PASSWORD}'
  MYSQL_DATABASE: '${VIPGO_WP_DB_USER}'
  MYSQL_USER: '${VIPGO_WP_DB_USER}'
  MYSQL_PASSWORD: '${VIPGO_WP_DB_PASSWORD}'
x-wordpress-envvars:
  VIRTUAL_HOST: '${VIPGO_DOMAIN}'
  WORDPRESS_DB_NAME: '${VIPGO_WP_DB_NAME}'
  WORDPRESS_DB_USER: '${VIPGO_WP_DB_USER}'
  WORDPRESS_DB_PASSWORD: '${VIPGO_WP_DB_PASSWORD}'
services:
  mariadb:
    cap_add:
      - SYS_PTRACE
    environment:
      MYSQL_ROOT_PASSWORD: '${VIPGO_MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${VIPGO_WP_DB_USER}'
      MYSQL_USER: '${VIPGO_WP_DB_USER}'
      MYSQL_PASSWORD: '${VIPGO_WP_DB_PASSWORD}'
    image: 'mariadb:10.3'
    ports:
      - '33306:3306'
    networks:
      - backend
    volumes:
      - './conf/mariadb/my.cnf:/etc/mysql/my.cnf:ro'
      - './conf/mariadb/conf.d:/etc/mysql/conf.d'
      - './data/mariadb:/var/lib/mysql:rw'

  memcached:
    image: 'memcached:1.6-alpine'
    command:
      - '-m 128 -vv -o modern'
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: "256M"

  nginx:
    cap_add:
      - SYS_PTRACE
    image: 'jwilder/nginx-proxy:alpine'
    environment:
      DHPARAM_GENERATION: false
      SSL_POLICY: Mozilla-Modern
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 208.67.222.222
      - 8.8.8.8
    ports:
      - '80:80'
      - '443:443'
    networks:
      - frontend
      - backend
    deploy:
      resources:
        limits:
          memory: "128M"
    volumes:
      - wp:/var/www/html
      - './app/wp-content/client-mu-plugins:/var/www/html/wp-content/client-mu-plugins:rw'
      - './app/wp-content/images:/var/www/html/wp-content/images:rw'
      - './app/wp-content/languages:/var/www/html/wp-content/languages:rw'
      - './app/wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins:rw'
      - './app/wp-content/plugins:/var/www/html/wp-content/plugins:rw'
      - './app/wp-content/themes:/var/www/html/wp-content/themes:rw'
      - './app/wp-content/uploads:/var/www/html/wp-content/uploads:rw'
      - './app/wp-content/vip-config:/var/www/vip-config:rw'
      - './conf/nginx/certs:/etc/nginx/certs'
      - './conf/nginx/conf.d/upstream-media-host:/etc/nginx/conf.d/upstream-media-host:ro'
      - './conf/nginx/html:/usr/local/nginx/html'
      - './conf/nginx/vhost.d:/etc/nginx/vhost.d:ro'
      - './conf/nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro'
      - './conf/nginx/proxy.conf:/etc/nginx/proxy.conf:ro'
      - './data/nginx:/var/cache/nginx:rw'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'

  wordpress:
    cap_add:
      - SYS_PTRACE
    image: 'wpvip/wordpress:${VIPGO_PHP_VERSION}'
    domainname: wpvipgolocal.net
    environment:
      HTTPS_METHOD: noredirect
      HSTS: off
      VIRTUAL_HOST: '${VIPGO_DOMAIN}'
      WORDPRESS_DB_NAME: '${VIPGO_WP_DB_NAME}'
      WORDPRESS_DB_USER: '${VIPGO_WP_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${VIPGO_WP_DB_PASSWORD}'
      VIRTUAL_PROTO: fastcgi
      VIRTUAL_PORT: 9000
      VIRTUAL_ROOT: /var/www/html
      WORDPRESS_DB_HOST: mariadb
    extra_hosts:
      - "${VIPGO_DOMAIN}:127.0.0.1"
      - "host.docker.internal:host-gateway"
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /var/log
    volumes:
      - wp:/var/www/html
      - './conf/wordpress/php/ray.php:/var/www/html/ray.php:ro'
      - './app/wp-content/client-mu-plugins:/var/www/html/wp-content/client-mu-plugins:rw'
      - './app/wp-content/images:/var/www/html/wp-content/images:rw'
      - './app/wp-content/languages:/var/www/html/wp-content/languages:rw'
      - './app/wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins:rw'
      - './app/wp-content/plugins:/var/www/html/wp-content/plugins:rw'
      - './app/wp-content/themes:/var/www/html/wp-content/themes:rw'
      - './app/wp-content/uploads:/var/www/html/wp-content/uploads:rw'
      - './app/wp-content/vip-config:/var/www/vip-config:rw'
      - './app/wp-content/mu-plugins/drop-ins/object-cache/object-cache-stable.php:/var/www/html/wp-content/object-cache.php:r'
      - './conf/wordpress/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
      - './conf/wordpress/conf.d/zzz-wpvipgo-dev.ini:/usr/local/etc/php/conf.d/zzz-wpvipgo-dev.ini'
      - './conf/wordpress/php/env.php:/usr/local/etc/php/env.php'
    networks:
      - backend
    depends_on:
      - nginx
      - memcached
      - mariadb

  cli:
    image: 'wpvip/cli:${VIPGO_PHP_VERSION}'
    domainname: wpvipgolocal.net
    environment:
      WORDPRESS_DB_NAME: '${VIPGO_WP_DB_NAME}'
      WORDPRESS_DB_USER: '${VIPGO_WP_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${VIPGO_WP_DB_PASSWORD}'
      WORDPRESS_DB_HOST: mariadb
    extra_hosts:
      - "${VIPGO_DOMAIN}:127.0.0.1"
      - "host.docker.internal:host-gateway"
    volumes:
      - wp:/var/www/html
      - './conf/wordpress/php/ray.php:/var/www/html/ray.php:ro'
      - './app/wp-content/client-mu-plugins:/var/www/html/wp-content/client-mu-plugins:rw'
      - './app/wp-content/images:/var/www/html/wp-content/images:rw'
      - './app/wp-content/languages:/var/www/html/wp-content/languages:rw'
      - './app/wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins:rw'
      - './app/wp-content/plugins:/var/www/html/wp-content/plugins:rw'
      - './app/wp-content/themes:/var/www/html/wp-content/themes:rw'
      - './app/wp-content/uploads:/var/www/html/wp-content/uploads:rw'
      - './app/wp-content/vip-config:/var/www/vip-config:rw'
      - './app/wp-content/mu-plugins/drop-ins/object-cache/object-cache-stable.php:/var/www/html/wp-content/object-cache.php:r'
      - './conf/wordpress/conf.d/zzz-wpvipgo-dev.ini:/usr/local/etc/php/conf.d/zzz-wpvipgo-dev.ini'
      - './conf/wordpress/php/env.php:/usr/local/etc/php/env.php'
    networks:
      - backend
    depends_on:
      - memcached
      - mariadb
    command: '/bin/bash -c "trap : TERM INT; tail -f /dev/null & wait"'
    working_dir: /var/www/html

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
    networks:
      - frontend
      - backend
    deploy:
      resources:
        limits:
          memory: "128M"

networks:
  frontend:
    enable_ipv6: false
  backend:
    enable_ipv6: false

volumes:
  wp: {}
